default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  username: d3v17
  password: password
  socket: /var/run/postgresql

development:
  <<: *default
  database: job_development
production:
  <<: *default
  database: job_production
  username: d3v17
  password: password
test:
  <<: *default
  database: job_test
