default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  username: sarad
  password: 
  socket: /var/run/postgresql

development:
  <<: *default
  database: job_development

test:
  <<: *default
  database: job_test
